builds:
  - dir: .
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.name={{.ProjectName}} -X main.target={{.Os}}-{{.Arch}} -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: "{{.ProjectName}}"

archives:
  - name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    format: tar.gz
    files:
      - config.toml
      - README.md
      - LICENSE

release:
  github:
    owner: exithial
    name: autotile-cortile-fork
  # Reads human-friendly release notes from release_notes.txt
  body_template: "{{ readFile \"release_notes.txt\" }}"
  replace_existing_draft: true

checksum:
  name_template: "{{.ProjectName}}_{{.Version}}_checksums.txt"
